#                                                                        #
# Settings                                                               #
#                                                                        #

Documentation:
  defaultConfiguration:
    imageMaxWidth: 1500
    imageMaxHeight: 1000
    thumbnailMaxWidth: 710
    thumbnailMaxHeight: 800
    configurationRootPath: %FLOW3_PATH_PACKAGES%Documentation/Documentation/Configuration
    #imageRootPath: %FLOW3_PATH_PACKAGES%Documentation/Documentation/Documentation/Images
  bundles: []
#  bundles:
#    Quickstart:
#      importRootNodePath: 'documentation/quickstart'
#      documentationRootPath: %FLOW3_PATH_PACKAGES%Documentation/Documentation/Documentation/Quickstart
#      renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/Quickstart
  references:
    FluidViewHelpers:
      title: 'Fluid ViewHelper Reference'
      savePathAndFilename: '%FLOW3_PATH_PACKAGES%Documentation/Documentation/Documentation/TheDefinitiveGuide/PartV/FluidViewHelperReference.rst'
      affectedClasses:
        parentClassName: 'TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper'
        classNamePattern: '/^TYPO3\\Fluid\\ViewHelpers\\.*$/i'
      parser:
        implementationClassName: 'Documentation\Domain\Service\FluidViewHelperClassParser'
        options:
          namespaces:
            f: 'TYPO3\Fluid\ViewHelpers'
