#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  DocTools:
    defaultConfiguration:
      imageMaxWidth: 1500
      imageMaxHeight: 1000
      thumbnailMaxWidth: 710
      thumbnailMaxHeight: 800
      configurationRootPath: %FLOW3_PATH_PACKAGES%Documentation/TYPO3.DocTools/Configuration
      #imageRootPath: %FLOW3_PATH_PACKAGES%Documentation/TYPO3.DocTools/Documentation/Images
    bundles:
      TYPO3DocToolsHtml:
        documentationRootPath: %FLOW3_PATH_PACKAGES%Documentation/TYPO3.DocTools/Documentation/
        configurationRootPath: %FLOW3_PATH_PACKAGES%Documentation/TYPO3.DocTools/Resources/Private/Themes/TYPO3/
        renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TYPO3.DocTools/
        renderingOutputFormat: 'html'
