#                                                                        #
# Settings                                                               #
#                                                                        #

Documentation:
  defaultConfiguration:
    imageMaxWidth: 1000
    imageMaxHeight: 1000
    thumbnailMaxWidth: 710
    thumbnailMaxHeight: 800
    configurationRootPath: %FLOW3_PATH_PACKAGES%Application/Documentation/Configuration
    #imageRootPath: %FLOW3_PATH_PACKAGES%Application/Documentation/Documentation/Images
#  bundles:
#    Quickstart:
#      importRootNodePath: 'documentation/quickstart'
#      documentationRootPath: %FLOW3_PATH_PACKAGES%Application/Documentation/Documentation/Quickstart
#      renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/Quickstart
#    TheDefinitiveGuide:
#      importRootNodePath: 'documentation/guide'
#      documentationRootPath: %FLOW3_PATH_PACKAGES%Application/Documentation/Documentation/TheDefinitiveGuide
#      renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide
