#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  DocTools:
    defaultConfiguration:
      imageMaxWidth: 1500
      imageMaxHeight: 1000
      thumbnailMaxWidth: 710
      thumbnailMaxHeight: 800
      renderByDefault: true

    bundles:
      TYPO3DocToolsHtml:
        documentationRootPath: %FLOW3_PATH_PACKAGES%Application/TYPO3.DocTools/Documentation/
        configurationRootPath: %FLOW3_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/TYPO3/
        renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TYPO3.DocTools/
        renderingOutputFormat: 'html'
        renderByDefault: false

      Quickstart:
        documentationRootPath: %FLOW3_PATH_PACKAGES%Framework/TYPO3.FLOW3/Documentation/Quickstart
        configurationRootPath: %FLOW3_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/FLOW3/
        renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/Quickstart/
        imageRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/Quickstart/_images/

      TheDefinitiveGuide:
        documentationRootPath: %FLOW3_PATH_PACKAGES%Framework/TYPO3.FLOW3/Documentation/TheDefinitiveGuide
        configurationRootPath: %FLOW3_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/FLOW3/
        renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/
        imageRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/_images/

      CodingGuidelines:
        documentationRootPath: %FLOW3_PATH_PACKAGES%Framework/TYPO3.FLOW3/Documentation/TheDefinitiveGuide/PartV/CodingGuideLines
        configurationRootPath: %FLOW3_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/FLOW3/
        renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/PartV/CodingGuidelines
        imageRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/_images/

    commandReference:
      title: 'FLOW3 Command Reference'
      savePathAndFilename: '%FLOW3_PATH_PACKAGES%Framework/TYPO3.FLOW3/Documentation/TheDefinitiveGuide/PartV/CommandReference.rst'

    references:
      FluidViewHelpers:
        title: 'Fluid ViewHelper Reference'
        savePathAndFilename: '%FLOW3_PATH_PACKAGES%Framework/TYPO3.FLOW3/Documentation/TheDefinitiveGuide/PartV/FluidViewHelperReference.rst'
        affectedClasses:
          parentClassName: 'TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper'
          classNamePattern: '/^TYPO3\\Fluid\\ViewHelpers\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FluidViewHelperClassParser'
          options:
            namespaces:
              f: 'TYPO3\Fluid\ViewHelpers'
      Flow3Validators:
        title: 'FLOW3 Validator Reference'
        savePathAndFilename: '%FLOW3_PATH_PACKAGES%Framework/TYPO3.FLOW3/Documentation/TheDefinitiveGuide/PartV/ValidatorReference.rst'
        affectedClasses:
          parentClassName: 'TYPO3\FLOW3\Validation\Validator\AbstractValidator'
          classNamePattern: '/^TYPO3\\FLOW3\\Validation\\Validator\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\Flow3ValidatorClassParser'
