#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  DocTools:
    defaultConfiguration:
      imageMaxWidth: 1500
      imageMaxHeight: 1000
      thumbnailMaxWidth: 710
      thumbnailMaxHeight: 800
      renderByDefault: true
      nodeTypes:
        page: 'TYPO3.Neos:Page'
        section: 'TYPO3.Neos:ContentCollection'
        text: 'TYPO3.Neos.NodeTypes:Text'
