#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  DocTools:
    defaultConfiguration:
      imageMaxWidth: 1500
      imageMaxHeight: 1000
      thumbnailMaxWidth: 710
      thumbnailMaxHeight: 800
      renderByDefault: true
      nodeTypes:
        page: 'TYPO3.Neos:Page'
        section: 'TYPO3.Neos:ContentCollection'
        text: 'TYPO3.Neos.NodeTypes:Text'

    bundles:
      TYPO3DocToolsHtml:
        documentationRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.DocTools/Documentation/'
        configurationRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/TYPO3/'
        renderedDocumentationRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/TYPO3.DocTools/'
        renderingOutputFormat: 'html'
        renderByDefault: false

      Quickstart:
        documentationRootPath: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/Quickstart'
        configurationRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/Flow/'
        renderedDocumentationRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/Quickstart/'
        imageRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/Quickstart/_images/'

      TheDefinitiveGuide:
        documentationRootPath: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide'
        configurationRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/Flow/'
        renderedDocumentationRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/'
        imageRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/_images/'

      CodingGuidelines:
        documentationRootPath: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/CodingGuideLines'
        configurationRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/Flow/'
        renderedDocumentationRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/PartV/CodingGuidelines'
        imageRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/TheDefinitiveGuide/_images/'

    commandReferences:
      FlowCommands:
        title: 'Flow Command Reference'
        packageKeys:
          - 'TYPO3.Flow'
          - 'TYPO3.Party'
          - 'TYPO3.Fluid'
          - 'TYPO3.Kickstart'
          - 'TYPO3.Welcome'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/CommandReference.rst'
      NeosCommands:
        title: 'Neos Command Reference'
        packageKeys:
          - 'TYPO3.Neos'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Application/TYPO3.Neos/Documentation/Appendixes/CommandReference.rst'

    references:
      FluidViewHelpers:
        title: 'Fluid ViewHelper Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/FluidViewHelperReference.rst'
        affectedClasses:
          parentClassName: 'TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper'
          classNamePattern: '/^TYPO3\\Fluid\\ViewHelpers\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FluidViewHelperClassParser'
          options:
            namespaces:
              f: 'TYPO3\Fluid\ViewHelpers'
      MediaViewHelpers:
        title: 'Media ViewHelper Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Application/TYPO3.Neos/Documentation/Appendixes/MediaViewHelperReference.rst'
        affectedClasses:
          parentClassName: 'TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper'
          classNamePattern: '/^TYPO3\\Media\\ViewHelpers\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FluidViewHelperClassParser'
          options:
            namespaces:
              'typo3.media': 'TYPO3\Media\ViewHelpers'
      NeosViewHelpers:
        title: 'Neos ViewHelper Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Application/TYPO3.Neos/Documentation/Appendixes/ViewHelperReference.rst'
        affectedClasses:
          parentClassName: 'TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper'
          classNamePattern: '/^TYPO3\\Neos\\ViewHelpers\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FluidViewHelperClassParser'
          options:
            namespaces:
              f: 'TYPO3\Fluid\ViewHelpers'
              neos: 'TYPO3\Neos\ViewHelpers'
      FlowValidators:
        title: 'Flow Validator Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ValidatorReference.rst'
        affectedClasses:
          parentClassName: 'TYPO3\Flow\Validation\Validator\AbstractValidator'
          classNamePattern: '/^TYPO3\\Flow\\Validation\\Validator\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FlowValidatorClassParser'
      FlowSignals:
        title: 'Flow Signals Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/SignalsReference.rst'
        affectedClasses:
          classesContainingMethodsAnnotatedWith: 'TYPO3\Flow\Annotations\Signal'
          classNamePattern: '/^TYPO3\\Flow\\.*$/i'
          includeAbstractClasses: TRUE
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\SignalsParser'
      NeosSignals:
        title: 'Neos Signals Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Application/TYPO3.Neos/Documentation/Appendixes/SignalsReference.rst'
        affectedClasses:
          classesContainingMethodsAnnotatedWith: 'TYPO3\Flow\Annotations\Signal'
          classNamePattern: '/^TYPO3\\(Neos|TYPO3CR)\\.*$/i'
          includeAbstractClasses: TRUE
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\SignalsParser'
      FlowTypeConverters:
        title: 'Flow TypeConverter Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/TypeConverterReference.rst'
        affectedClasses:
          parentClassName: 'TYPO3\Flow\Property\TypeConverter\AbstractTypeConverter'
          classNamePattern: '/^TYPO3\\Flow\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FlowTypeConverterClassParser'
      FlowAnnotations:
        title: 'Flow Annotation Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Framework/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/AnnotationReference.rst'
        affectedClasses:
          classNamePattern: '/^TYPO3\\Flow\\Annotations\\.*$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FlowAnnotationClassParser'
      FlowQueryOperations:
        title: 'FlowQuery Operation Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Application/TYPO3.Neos/Documentation/Appendixes/FlowQueryOperationReference.rst'
        affectedClasses:
          interface: 'TYPO3\Eel\FlowQuery\OperationInterface'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\FlowQueryOperationClassParser'
      EelHelpers:
        title: 'Eel Helpers Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Application/TYPO3.Neos/Documentation/Appendixes/EelHelpersReference.rst'
        affectedClasses:
          interface: 'TYPO3\Eel\ProtectedContextAwareInterface'
          classNamePattern: '/^.*Helper$/i'
        parser:
          implementationClassName: 'TYPO3\DocTools\Domain\Service\EelHelperClassParser'
